language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1

before_install:
  - rm .gemfiles/Gemfile.rspec.lock || true
  - rm .gemfiles/Gemfile.ruby193.rspec.lock || true
  - rm .gemfiles/Gemfile.ruby200.rspec.lock || true

gemfile:
  - .gemfiles/Gemfile.rspec
  - .gemfiles/Gemfile.ruby193.rspec

script:
 - "STRICT_VARIABLES=no bundle exec rake spec SPEC_OPTS='--format documentation'"

env:
  - PUPPET_VERSION="~> 4.5.0"
  - PUPPET_VERSION="~> 4.6.0"
  - PUPPET_VERSION="~> 4.7.0"
  - PUPPET_VERSION="~> 4.8.0"
  - PUPPET_VERSION="~> 5.0.0"
  - PUPPET_VERSION="~> 5.1.0"
  - PUPPET_VERSION="~> 5.2.0"
  - PUPPET_VERSION="~> 5.3.0"
  - PUPPET_VERSION="~> 5.4.0"
  - PUPPET_VERSION="~> 5.5.0"
  - PUPPET_VERSION="~> 6.4.0"
  - PUPPET_VERSION="~> 6.10.0"
  - PUPPET_VERSION="~> 6.13.0"

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: .gemfiles/Gemfile.ruby187.rspec
    - rvm: 1.9.3
      gemfile: .gemfiles/Gemfile.rspec
    - rvm: 2.0.0
      gemfile: .gemfiles/Gemfile.ruby187.rspec
    - rvm: 2.0.0
      gemfile: .gemfiles/Gemfile.ruby193.rspec
    - rvm: 2.1.1
      gemfile: .gemfiles/Gemfile.ruby187.rspec
    - rvm: 2.1.1
      gemfile: .gemfiles/Gemfile.ruby193.rspec
